import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import ClientLayout from './ClientLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: 0, padding: 0 }}>
        <ClientLayout>
          <main className="main-content" style={{ margin: 0, padding: 0 }}>
            {children}
          </main>
        </ClientLayout>
      </body>
    </html>
  );
}
